# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20170808_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynovel',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
