# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_mynovel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynovel',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('f', 'Finished'), ('p', 'Published')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
